//! Type-safe sub-agent configuration for Claude Code.
//!
//! Agent YAML files live in `.claude/agents/*.yaml` and are read by Claude Code
//! at session startup. The `description` field is the trigger — Claude reads it
//! to decide whether to delegate a task to this agent.
//!
//! Generated by `cargo run -p agent-gen` — do not edit the YAML files by hand.
//! Edit the typed definitions in `crates/agent-gen/src/agents.rs` instead.
//!
//! Spec: https://code.claude.com/docs/en/sub-agents

use serde::{Deserialize, Serialize};

// ── Model IDs ─────────────────────────────────────────────────────────────────

/// Pinned Claude model identifiers.
///
/// Keep these in sync with the `inferenceModels` list in macOS profiles
/// (`profiles/claude_desktop_*.json`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AgentModel {
    /// Best for complex multi-step reasoning; highest cost.
    #[serde(rename = "claude-opus-4-8")]
    Opus48,

    /// Balanced speed + intelligence; recommended default for most agents.
    #[serde(rename = "claude-sonnet-4-6")]
    Sonnet46,

    /// Fastest and cheapest; good for well-scoped mechanical tasks.
    #[serde(rename = "claude-haiku-4-5-20251001")]
    Haiku45,
}

impl AgentModel {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Opus48   => "claude-opus-4-8",
            Self::Sonnet46 => "claude-sonnet-4-6",
            Self::Haiku45  => "claude-haiku-4-5-20251001",
        }
    }
}

// ── Tools ─────────────────────────────────────────────────────────────────────

/// Built-in Claude Code tools.
///
/// Only list tools the agent actually needs — principle of least privilege.
/// This list is validated at generation time so typos fail the build.
///
/// Full reference: https://claude.com/docs/cowork/3p/configuration#disabledBuiltinTools
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AgentTool {
    /// Run shell commands on the host.
    Bash,
    /// Read files.
    Read,
    /// Write new files.
    Write,
    /// Edit existing files (surgical patch, cheaper than Write).
    Edit,
    /// Glob file patterns.
    Glob,
    /// Grep file contents.
    Grep,
    /// Spawn a background sub-agent (nesting depth limited to 3).
    Task,
    /// Create a task in the task list widget.
    TaskCreate,
    /// Update a task in the task list widget.
    TaskUpdate,
    /// Get a task from the task list widget.
    TaskGet,
    /// List tasks in the task list widget.
    TaskList,
    /// Stop a running task.
    TaskStop,
    /// Fetch a URL.
    WebFetch,
    /// Web search.
    WebSearch,
    /// Invoke a skill.
    Skill,
    /// Ask the user a multiple-choice question.
    AskUserQuestion,
    /// Edit Jupyter notebook cells.
    NotebookEdit,
    /// Run JavaScript in the REPL.
    JavaScript,
    /// Write todo items.
    TodoWrite,
    /// Search for deferred tools.
    ToolSearch,
    /// Send a message to the user.
    SendUserMessage,
}

impl AgentTool {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Bash             => "Bash",
            Self::Read             => "Read",
            Self::Write            => "Write",
            Self::Edit             => "Edit",
            Self::Glob             => "Glob",
            Self::Grep             => "Grep",
            Self::Task             => "Task",
            Self::TaskCreate       => "TaskCreate",
            Self::TaskUpdate       => "TaskUpdate",
            Self::TaskGet          => "TaskGet",
            Self::TaskList         => "TaskList",
            Self::TaskStop         => "TaskStop",
            Self::WebFetch         => "WebFetch",
            Self::WebSearch        => "WebSearch",
            Self::Skill            => "Skill",
            Self::AskUserQuestion  => "AskUserQuestion",
            Self::NotebookEdit     => "NotebookEdit",
            Self::JavaScript       => "JavaScript",
            Self::TodoWrite        => "TodoWrite",
            Self::ToolSearch       => "ToolSearch",
            Self::SendUserMessage  => "SendUserMessage",
        }
    }
}

// ── Agent config ──────────────────────────────────────────────────────────────

/// Complete configuration for a Claude Code sub-agent.
///
/// Serializes to the YAML format expected in `.claude/agents/*.yaml`.
/// The `description` is the most important field — it must be specific
/// enough that Claude delegates the right tasks to this agent and nothing else.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentConfig {
    /// Machine-readable identifier, used as the YAML filename (`{name}.yaml`).
    /// Lowercase, hyphens only.
    pub name: String,

    /// Human + LLM-readable trigger description. Claude reads this to decide
    /// whether to delegate. Should answer: "delegate when the user wants to…"
    /// Include anti-patterns (what NOT to use this agent for) for precision.
    pub description: String,

    /// Model to use. Omit to inherit from the parent session.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<AgentModel>,

    /// Tools this agent may use. Omit or leave empty for the default tool set.
    /// Prefer an explicit allowlist — it prevents scope creep in the agent.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tools: Vec<AgentTool>,

    /// Maximum number of agentic turns. Prevents runaway loops.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_turns: Option<u32>,

    /// The system prompt injected into this agent's context window.
    /// Keep it concise and task-specific — the agent starts cold on every
    /// invocation and only has what's here plus what the parent passes.
    pub system_prompt: String,
}

impl AgentConfig {
    /// Validate the config at build time (panics on invalid state).
    pub fn validate(&self) {
        assert!(
            !self.name.is_empty() && self.name.chars().all(|c| c.is_ascii_alphanumeric() || c == '-'),
            "agent name must be [a-z0-9-]: {:?}", self.name
        );
        assert!(self.description.len() >= 20, "description too short for agent {:?}", self.name);
        assert!(!self.system_prompt.is_empty(), "system_prompt empty for agent {:?}", self.name);
    }

    /// Serialize to the YAML string expected in `.claude/agents/{name}.yaml`.
    ///
    /// The output YAML uses `system_prompt` as a block scalar so multi-line
    /// prompts render cleanly in text editors and diffs.
    pub fn to_yaml(&self) -> String {
        // Build output manually to control key ordering and block scalars.
        let mut out = String::new();

        out.push_str("# Generated by `cargo run -p agent-gen` — do not edit by hand.\n");
        out.push_str("# Source: crates/agent-gen/src/agents.rs\n\n");

        out.push_str(&format!("name: {}\n", self.name));

        // Description as a block scalar for readability in diffs.
        out.push_str("description: |\n");
        for line in self.description.lines() {
            out.push_str(&format!("  {line}\n"));
        }

        if let Some(model) = &self.model {
            out.push_str(&format!("model: {}\n", model.as_str()));
        }

        if !self.tools.is_empty() {
            out.push_str("tools:\n");
            for tool in &self.tools {
                out.push_str(&format!("  - {}\n", tool.as_str()));
            }
        }

        if let Some(max) = self.max_turns {
            out.push_str(&format!("max_turns: {max}\n"));
        }

        // System prompt as a block scalar — critical for multi-line readability.
        out.push_str("system_prompt: |\n");
        for line in self.system_prompt.lines() {
            if line.is_empty() {
                out.push('\n');
            } else {
                out.push_str(&format!("  {line}\n"));
            }
        }

        out
    }
}
