[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold", "-Ctarget-cpu=native"]
[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]
[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static"]
[build]
# jobs defaults to num_cpus
incremental = true
# To use sccache locally: export RUSTC_WRAPPER=sccache
[registries.crates-io]
protocol = "sparse"
[net]
git-fetch-with-cli = true
[profile.dev]
opt-level = 0
debug = 1
split-debuginfo = "unpacked"
[profile.dev.package."*"]
opt-level = 3
[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
[profile.quick]
inherits = "dev"
opt-level = 1
debug = 0
