#!/usr/bin/env npx ts-node
/**
 * Generate .claude/agents/*.yaml from typed TypeScript definitions.
 *
 * Usage:
 *   npx ts-node scripts/agents/generate.ts           # write .claude/agents/
 *   npx ts-node scripts/agents/generate.ts --check   # validate only (CI)
 *   npx ts-node scripts/agents/generate.ts --print   # print to stdout
 *   npx ts-node scripts/agents/generate.ts --out <dir>
 *
 * Equivalent to `cargo run -p agent-gen` — both produce identical YAML.
 * Choose based on your toolchain preference. The Rust version is faster.
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { AgentConfig } from './schema.js';
import { agents } from './agents.js';

const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const printOnly = args.includes('--print');
const outIdx = args.indexOf('--out');
const outDir = outIdx >= 0 ? args[outIdx + 1] : '.claude/agents';

// ── Validate ──────────────────────────────────────────────────────────────────

const errors: string[] = [];

for (const raw of agents) {
  const result = AgentConfig.safeParse(raw);
  if (!result.success) {
    errors.push(`${raw.name}: ${result.error.issues.map(i => i.message).join('; ')}`);
  }
}

if (errors.length > 0) {
  console.error('✗ validation failed:');
  for (const e of errors) console.error('  ✗', e);
  process.exit(1);
}

const validated = agents.map(a => AgentConfig.parse(a));
console.log(`✓ validated ${validated.length} agents`);

if (checkOnly) {
  console.log('✓ check passed — no files written');
  process.exit(0);
}

// ── Serialize to YAML ─────────────────────────────────────────────────────────

function toYaml(a: AgentConfig): string {
  const lines: string[] = [
    '# Generated by `npx ts-node scripts/agents/generate.ts` — do not edit by hand.',
    '# Source: scripts/agents/agents.ts',
    '',
    `name: ${a.name}`,
    'description: |',
    ...a.description.split('\n').map(l => `  ${l}`),
  ];

  if (a.model) lines.push(`model: ${a.model}`);

  if (a.tools.length > 0) {
    lines.push('tools:');
    for (const t of a.tools) lines.push(`  - ${t}`);
  }

  if (a.max_turns !== undefined) lines.push(`max_turns: ${a.max_turns}`);

  lines.push('system_prompt: |');
  for (const l of a.system_prompt.split('\n')) {
    lines.push(l.trim() === '' ? '' : `  ${l}`);
  }

  return lines.join('\n') + '\n';
}

// ── Emit ──────────────────────────────────────────────────────────────────────

if (printOnly) {
  for (const a of validated) {
    console.log(`\n# ─── ${a.name} ─────────────────────────`);
    process.stdout.write(toYaml(a));
  }
  process.exit(0);
}

mkdirSync(outDir, { recursive: true });

let written = 0;
for (const a of validated) {
  const path = join(outDir, `${a.name}.yaml`);
  const content = toYaml(a);
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (existing === content) {
    console.log(`  ─ unchanged: ${path}`);
  } else {
    writeFileSync(path, content, 'utf8');
    console.log(`  ✓ wrote:     ${path}`);
    written++;
  }
}

console.log(`✓ ${written} file(s) written to ${outDir}`);
